name: remote ssh command
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          cd ${{ secrets.WORK_DIR }}
          rm -rf ${{ github.event.repository.name }}
          git clone https://github.com/RubelPerez/${{ github.event.repository.name }}.git -b ${{ secrets.MAIN_BRANCH }}
          cd ${{ github.event.repository.name }}
          exit
