name: remote ssh command
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: | 
          cd /home/repo
          rm -rf snipping_text_tool
          git clone https://github.com/RubelPerez/snipping_text_tool.git -b main
          cd snipping_text_tool
          "${{ github.event.repository.name }}" > hola.txt
          echo "hello world" > nota.txt
